version: '3.3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    network_mode: host
    hostname: localhost
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - springboot
    environment:
      TZ: Asia/Jakarta
    healthcheck:
      test: "exit 0"
  springboot:
    restart: always
    image: jerimkaura/oasis
    container_name: oasis
    ports:
      - 8080:8080
    network_mode: host
    hostname: localhost
    healthcheck:
      test: "exit 0"